stages:
  - lint
  - test

variables:
  PIP_CACHE_DIR: "$MODULE_30_CI_LINTERS/.cache/pip"

before_script:
  - python -V
  - pip install --upgrade pip
  - pip install -r requirements.txt

lint:
  stage: lint
  script:
    - pip install flake8
    - flake8 .

test:
  stage: test
  script:
    - pytest